### ISSUE TITLE
All authorize codes by default are inactive 

### ISSUE THREAD

**Issue by KMantas** [matthewhartstonge/storage#37]
hi

what is the reason for making all authorize codes inactive?
```
func toMongo(signature string, r fosite.Requester) storage.Request {
return storage.Request{
Active:            false,
```

In GetAuthorizeCodeSession there is a check  !req.Active 
Then by default if nothing else is done all authorize codes are invalid. Is some extra step required to make token active?
In example memory storage authorize codes by default are set to active:
```
func (s *MemoryStore) CreateAuthorizeCodeSession(_ context.Context, code string, req fosite.Requester) error {
	s.AuthorizeCodes[code] = StoreAuthorizeCode{active: true, Requester: req}
	return nil
}
```
thanks

**Comment by matthewhartstonge** [comment]
Well that explains where I got up to while documenting the change to the official mongo driver!

I'm planning on embedding the `fosite-example` repo with the relevant mongo tweaks within this repo, I have the code local - but got stuck on the auth code not returning (at which point I went to bed).

We've been using this for the client credential flow, but want to move to code based flow, so this is definitely a priority.
