### ISSUE TITLE
feature: add support for expiring token data

### ISSUE THREAD

**Issue by qkrgksqkr** [matthewhartstonge/storage#51]
How can I set the TTL?
I want to remove a document at expireAt time.

**Comment by matthewhartstonge** [comment]
Hey @qkrgksqkr you probably want to create a mongo index to deal with this within mongo itself, see the following:

- https://docs.mongodb.com/manual/tutorial/expire-data/#expire-documents-at-a-specific-clock-time

Hope that helps!
You can of course do this using the `mongo go driver` directly, you can see how this is done internally, for example in the [client manager](https://github.com/matthewhartstonge/storage/blob/14c1fab8f7d9b2def2804fd98f677044bbe40437/mongo/client_manager.go#L43-L65), there may be a client option to set expire after seconds via their API:

```go
// Configure sets up the Mongo collection for OAuth 2.0 client resources.
func (c *ClientManager) Configure(ctx context.Context) (err error) {
	log := logger.WithFields(logrus.Fields{
		"package":    "mongo",
		"collection": storage.EntityClients,
		"method":     "Configure",
	})

	// Build Index
	indices := []mongo.IndexModel{
		{
			Keys: bson.D{
				{
					Key:   "id",
					Value: int32(1),
				},
			},
			Options: options.Index().
				SetBackground(true).
				SetName(IdxClientID).
				SetSparse(true).
				SetUnique(true),
		},
	}

	collection := c.DB.Collection(storage.EntityClients)
	_, err = collection.Indexes().CreateMany(ctx, indices)
	if err != nil {
		log.WithError(err).Error(logError)
		return err
	}

	return nil
}
```

If that satisfies your use case, let me know and I'll close this ticket :)

**Comment by qkrgksqkr** [comment]
Thanks @matthewhartstonge
You mean that I need to modify this source? like this?.
I want to add TTL index named 'expireAt' like below.

`func (r *RequestManager) Configure(ctx context.Context) (err error) {
	// In terms of the underlying entity for session data, the model is the
	// same across the following entities. I have decided to logically break
	// them into separate collections rather than have a 'SessionType'.
	collections := []string{
		storage.EntityAccessTokens,
		storage.EntityAuthorizationCodes,
		storage.EntityOpenIDSessions,
		storage.EntityPKCESessions,
		storage.EntityRefreshTokens,
	}

	// Build Indices
	indices := []mongo.IndexModel{
		{
			Keys: bson.D{
				{
					Key:   "id",
					Value: int32(1),
				},
			},
			Options: options.Index().
				SetBackground(true).
				SetName(IdxSessionID).
				SetSparse(true).
				SetUnique(true),
		},
		{
			Keys: bson.D{
				{
					Key:   "signature",
					Value: int32(1),
				},
			},
			Options: options.Index().
				SetBackground(true).
				SetName(IdxSignatureID).
				SetSparse(true).
				SetUnique(true),
		},
		{
			Keys: bson.D{
				{
					Key:   "clientId",
					Value: int32(1),
				},
				{
					Key:   "userId",
					Value: int32(1),
				},
			},
			Options: options.Index().
				SetBackground(true).
				SetName(IdxCompoundRequester).
				SetSparse(true),
		},
               // start : I add source
		{
			Keys: bson.D{
				{
					Key:   "expiredAt",
					Value: int32(-1),
				},
			},
			Options: options.Index().
				SetBackground(true).
				SetName(IdxExpires).
				SetSparse(false).
				SetUnique(false).
				SetExpireAfterSeconds(1),
		},
                // End : I add source
	}

	for _, entityName := range collections {
		log := logger.WithFields(logrus.Fields{
			"package":    "mongo",
			"collection": entityName,
			"method":     "Configure",
		})

		collection := r.DB.Collection(entityName)
		_, err = collection.Indexes().CreateMany(ctx, indices)
		if err != nil {
			log.WithError(err).Error(logError)
			return err
		}
	}

	return nil`


But It's difficult for me change this source.
Could you update this features at your next update??
and , Adding 'expireAt' key every document, and it's value is same in session storage.
So everyToken containg expiretime has can 'expierAt'  TTL index in MongoDB.

**Comment by matthewhartstonge** [comment]
@qkrgksqkr ah I see, didn't quite read that it requires a mongo "date" typed field specifically. :confused: 

So yes, this would require an extra field in each model to enable TTL expiry.  I'm thinking the best way forward for this would be to add a new config option, where the TTL is configured in hours.

This way, if configured, the expiry field can be implemented by calling `time.Now().Add(time.Hour * time.Duration(config.TokenTTL))`:

```
TokenTTL  uint64      `default:"0"       envconfig:"CONNECTIONS_MONGO_TOKEN_TTL"`
```


For what it's worth, I've thought that using this mongo feature would be really handy for removing "dead" tokens based on the configured fosite session timings. Also makes database management a lot easier than remember to purge sessions every X number of weeks. So this will be a great feature to add :rocket:

**Comment by matthewhartstonge** [comment]
For now, if it helps, I've been manually cleaning this by running a mongo script based on the create time, similar to this (but expanded to handle batch deletes):

```js
function expireTokens(collection, expiry) {
  db.getCollection('accessTokens').deleteMany({
    createTime: {
      $lte: expiry
    }
  });
}

// The unix timestamp at which you want to remove tokens/sessions before 
var expiry = 1628073412;

// Execute removals
expireTokens('accessTokens', expiry);
expireTokens('refreshTokens', expiry);
expireTokens('authorizationCodes', expiry);
expireTokens('pkceSessions', expiry);
expireTokens('openIDConnectSessions', expiry);
```

^ FYI this script is not production ready.
 
- I have not tested the above script
- There is no index on createTime currently (unless you manually create an index on your own mongo collections) so this will perform a COLLSCAN
- With large collections, with no index on createTime, this will take a long time
- With large collections, with no index on createTime, the above script can cause mongo to lock up as it replicates the data out

**Comment by qkrgksqkr** [comment]
@matthewhartstonge

I will wait new features update.
I hope "Setting TTL Index" feature can be implemented using new config option (TokenTTL)

`TokenTTL  uint64      `default:"0"       envconfig:"CONNECTIONS_MONGO_TOKEN_TTL"``

It's very simple to use.
I expect yor new Tags

Thank you for help.

**Comment by qkrgksqkr** [comment]
Hello~ @matthewhartstonge 
Do you have a schedule about this feature?
Thank you.

**Comment by matthewhartstonge** [comment]
Hey, not currently. Got a number of things in flight at the moment.

Had a good look a week back, but decided that it would be a pain/would be non-best practice to send it via the context.

So needed to come up with a better way to wire it in so that it's able to be supported by any storage backend. 

Probably something like:

```go
type Expirer interface {
  ConfigureExpiry() error
}
```

**Comment by qkrgksqkr** [comment]
@matthewhartstonge 
Thany you for your update!!!
